@LivlReviewsApi_HostAddress = http://localhost:5231

GET {{LivlReviewsApi_HostAddress}}/weatherforecast/
Accept: application/json

GET {{LivlReviewsApi_HostAddress}}/send-invitation-email
Accept: application/json

###