name: Test application

on:
  pull_request: 
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.104

    - name: Install dependencies
      run: dotnet restore ./LivlReviewsApi && dotnet restore ./LivlReviewsApiTests

    - name: Build
      run: dotnet build ./LivlReviewsApi --configuration Release --no-restore

    - name: Test
      run: dotnet test ./LivlReviewsApiTests/ --no-restore --verbosity normal

